firefly_flask/app/models.py
from . import db
from sqlalchemy.dialects.mysql import LONGTEXT

class Search(db.Model):
    __tablename__ = 'spots'
    id = db.Column(db.Integer, primary_key=True)
    search_string = db.Column(db.Text)
    lat = db.Column(db.Float)
    lon = db.Column(db.Float)
    location_name = db.Column(db.Text)
    json_result = db.Column(LONGTEXT)

class Photo(db.Model):
    __tablename__ = 'photos'
    id = db.Column(db.Integer, primary_key=True)
    spotname = db.Column(db.Text)
    source_id = db.Column(db.Text)
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    tags = db.Column(db.Text)
    views = db.Column(db.Integer)
    favourites = db.Column(db.Integer)
    comments = db.Column(db.Integer)
    username = db.Column(db.Text)
    photo_url = db.Column(db.Text)
    search_id = db.Column(db.ForeignKey(Search.id),nullable=False)

firefly_flask/app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import Required

class SearchForm(Form):
    search_query = StringField('Where do you want to photograph?', validators=[Required()])
    submit = SubmitField('Submit')

firefly_flask/app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.moment import Moment
from flask.ext.sqlalchemy import SQLAlchemy
from config import config

bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

firefly_flask/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

firefly_flask/app/main/views.py
from flask import render_template, redirect, url_for, current_app
from .. import db
from ..models import  Search,Photo
from . import main
from .forms import SearchForm
import requests

@main.route('/', methods=['GET', 'POST'])
def index():
    form = SearchForm()
    if form.validate_on_submit():
        search_query = form.search_query.data
        return redirect(url_for('main.search',search_query = search_query))
    else:
        return render_template('index.html',form = form)

@main.route('/search/<search_query>', methods=['GET', 'POST'])
def search(search_query = None):
    search_query = search_query.title()
    form = SearchForm()
    if form.validate_on_submit():
        return redirect(url_for('main.search', search_query=form.search_query.data.title()))
    form.search_query.data = search_query.title()
    return render_template('search.html',form = form, query = search_query.title())

@main.route('/about')
def about():
    return render_template('about.html')

@main.route('/why')
def why():
    return render_template('why.html')

@main.route('/tech_stack')
def tech_stack():
    return render_template('tech_stack.html')

firefly_flask/app/templates/about.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} visitfirefly.de - Find hidden places to take great pictures{% endblock %}

{% block page_content %}
    <div class="page-header">

      <img src="/static/hackathon_icon.jpg" class="img-responsive" style="max-width: 40px; width:100%; height:auto; align:left; margin-right:10px; display:inline;"> This is a small hackathon project created on the Trivago Hackathon 2015.
      The topic is/was "<b>a new way of travelling</b>".<br>
      <br>
      <h3><img src="/static/package_icon.png" class="img-responsive" style="max-width: 40px; width:100%; height:auto; align:left; margin-right:10px; display:inline;"> Code repository</h3><br>
      <a href="https://github.com/TrivagoHackathonFirefly/project" target="_blank">TrivagoHackathonFirefly @ Github</a><br><br>
      <h3><img src="/static/twitter.png" class="img-responsive" style="max-width: 40px; width:100%; height:auto; align:right; margin-right:10px; display:inline;"> Twitter account</h3><br>
      <a href="https://twitter.com/DEfirefly" target="_blank"><b>@DEfirefly</b></a><br><br> 
      <h3><img src="/static/team.png" class="img-responsive" style="max-width: 40px; width:100%; height:auto; align:right; margin-right:10px; display:inline;"> Team members</h3><br>
      <br>
      <div class="row">
        <div class="col-md-6">
          <div class "row">
            <b>Daniel Espendiller</b><br>
            <img src="/static/daniele.png" class="img-responsive" style="max-width: 320px; width:100%; height:auto; align:right; padding-right:6px;"><br><br>
          </div>
        </div>
        <div class="col-md-6">
          <div class="row">
            <b>Markus Rekkenbeil</b><br>
            <img src="/static/markusr.jpg" class="img-responsive" style="max-width: 320px; width:100%; height:auto; align:right; padding-right:6px;"><br><br>
          </div>
        </div>
        <div class="col-md-6">
          <div class="row">
            <b>Tobias Siebenlist</b><br>
            <img src="/static/tobiass.jpg" class="img-responsive" style="max-width: 320px; width:100%; height:auto; align:right; padding-right:6px;"><br><br>
          </div>
        </div>
        <div class="col-md-6">
          <div class="row">
            <b>Jens Terliesner</b><br>
            <img src="/static/jenst.jpg" class="img-responsive" style="max-width: 320px; width:100%; height:auto; align:right; padding-right:6px;"><br><br>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

firefly_flask/app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Visit the firefly{% endblock %}

{% block head %}
{{ super() }}
<link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet" type="text/css">
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Visit the firefly</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                <li><a href="{{ url_for('main.about') }}">About</a></li>
                <li><a href="{{ url_for('main.tech_stack') }}">Technology stack</a></li>




            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 50px">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}


{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

firefly_flask/app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} visitfirefly.de - Find hidden places to take great pictures{% endblock %}

{% block page_content %}
        <h1><img src="/static/firefly.svg" alt="The Firefly Logo" class="img-responsive" style="width:10%; height:auto; align:right; padding-right:6px;">Welcome to visit the firefly!</h1> Type a <b>destination</b> to find hidden places to take great photos!<br></br>

        <div class="container-fluid">
            <form method="post" class="form" role="form">
            <div class = 'col-xs-4 col-md-4'>

            {{ form .hidden_tag()}}

                <div class="form-group "><input class="form-control" id="search_query" name="search_query" type="text" placeholder = "Where do you want to search the firefly?"value="{{query}}" >
                </div>
            </div>

            <div class = 'col-xs-6 col-md-4'>

            <input class="btn btn-default" id="submit" name="submit" type="submit" value="Submit" style = 'display:inline;' ></div>
        </div>
    
{% endblock %}

firefly_flask/app/templates/search.html
{% extends "base.html" %}


{% import "bootstrap/wtf.html" as wtf %}

{% block title %} visitfirefly.de - Find hidden places to take great pictures{% endblock %}

{% block page_content %}
<br></br>
    <div class="container-fluid">
        <form method="post" class="form" role="form">

            <div class = 'col-xs-4 col-md-4'>

            {{ form .hidden_tag()}}

        <div class="form-group "><input class="form-control" id="search_query" name="search_query" type="text" placeholder = "Where do you want to search the firefly?"value="{{query}}" ></div>
        </div>

        <div class = 'col-xs-6 col-md-4'>

            <input class="btn btn-default" id="submit" name="submit" type="submit" value="Submit" style = 'display:inline;' ></div>
  </div>

</form>
    </div>

<div class="map-canvas-wrap">
    <div id="map-canvas" data-uri="http://visitfirefly.de/photos/{lat}/{lng}" data-hotels="http://visitfirefly.de/hotels/{lat}/{lng}" data-q="{{ query }}"></div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="image"></div>
                    </div>

                    <div class="col-md-4">
                        <div class="row sub-image"></div>
                    </div>

                </div>
                <div class="hotel-ad hide">
                    <hr>
                    <div class="text-muted pull-right">Next Hotel <span class="ad-dist"></span></div>
                    <div class="row">
                        <div class="col-md-2">
                            <img src="http://lorempixel.com/400/200/" width="80">
                        </div>
                        <div class="col-md-6">
                            <h2 style="font-size: 14px; margin:0; padding: 0; font-weight: bold" class="ad-title">Title</h2>
                            <p class="ad-dec">Description</p>
                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <div class="pull-left">
                    <span class="desc"></span><br/>
                    <span class="views pull-left"></span>
                </div>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=visualization,places"></script>
<script src="http://visitfirefly.de/static/richmarker.js"></script>
<script src="http://visitfirefly.de/static/map.js"></script>
{% endblock %}

firefly_flask/app/templates/tech_stack.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} visitfirefly.de - Find hidden places to take great pictures{% endblock %}

{% block page_content %}
    <div class="page-header">
      <h2>We are using the following technology stacks:</h2>
      <ul style="list-style-type:square">
        <li>Python Flask + Bootstrap</li>
        <li>JavaScript</li>
        <li>Nginx webserver + uSWGI + FastCGI</li>
        <li>MariaDB MySQL</li>
      </ul><br><br>
      <h2>The following APIs are in use:</h2>
      <ul style="list-style-type:square">
        <li>Flickr API for photos</li>
        <li>Google Maps JavaScript API for Heatmap Layer</li>
      </ul>
    </div>
{% endblock %}

firefly_flask/app/templates/why.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} visitfirefly.de - Find hidden places to take great pictures{% endblock %}

{% block page_content %}
    <div class="page-header">
    - Are <b>YOU</b> looking for hidden places to make great photos?<br>
    - <b>YOU</b> are not the typical photographer?!<br>
    <br>
    <h1>Try out firefly - your helping light for hidden places! </h1> 
    </div>
{% endblock %}